### ISSUE TITLE
Rag Demo To-Do List

### ISSUE THREAD

**Issue by chrisahsiong23** [intel/optimized-cloud-recipes#28]
@wsfowler
Folder: [recipes/ai-rag-amx-ubuntu]

- [ ] Make sure the display on app is representative of the dataset being used (Chris)
- [x] We need to create the AWS example on Terraform (Fowler)
- [x] Write ansible code to app (Chris)
- [x] Make sure that all the imports in the app are needed – clean up (Chris)
- [x] Update contributors list (Chris)
- [x] Find link to model on Huggingface – add it to app (Josh)
- [ ] Add in different 5th dataset (Chris)
- [ ] Credit developer who created jupyter notebook (Chris)
- [x] Clean up variables in run_rag function (Chris)
- [x] Passing the URL in JSON form – look into this (Chris)
- [ ] Possibly add a different model (Josh)
